version: '3.9'

services:
  backend:
    build: .
    container_name: job_backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_NAME: jobapp_db
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: job_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jobapp_db
    ports:
      - "5432:5432"
    volumes:
      - /Users/MANOJ/Coding/job-app-db-cont:/var/lib/postgresql/data
